spring.application.name=Nhom02_InventoryProcessingUnit
server.port=8084
spring.data.redis.url=rediss://default:gQAAAAAAAUa-AAIgcDE3MzM0M2FkMWYzYjE0ZjczODJjNDE1Njk5YmQ3YjZiMA@concrete-pegasus-83646.upstash.io:6379